name: example
description: I18next example project

version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.38.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  i18next:
    path: ../
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    # flutter asset generator/resolver isn't able to deal with wildcards yet
    # due to how asset resolution works (1x, 2x, 3x, ...)
    # for now, we'll have to add them manually
    - localizations/en-US/
    - localizations/pt-BR/
