name: i18next
description: A localization formatter based on the i18next standard. It is not yet a fully i18n tool only the formatting itself.
version: 0.7.1
repository: https://github.com/williamhjcho/i18next
homepage: https://github.com/williamhjcho/i18next

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0

flutter:
